# Generated by Django 4.2.7 on 2026-01-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('source', models.CharField(max_length=200, verbose_name='Fonte')),
                ('rows_processed', models.IntegerField(default=0, verbose_name='Linhas Processadas')),
                ('matches_created', models.IntegerField(default=0, verbose_name='Partidas Criadas')),
                ('matches_skipped', models.IntegerField(default=0, verbose_name='Partidas Ignoradas')),
                ('errors', models.TextField(blank=True, verbose_name='Erros')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluido'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluido em')),
            ],
            options={
                'verbose_name': 'Log de Importacao',
                'verbose_name_plural': 'Logs de Importacao',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='Regiao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('oe_teamid', models.CharField(blank=True, help_text="Identificador unico do time no Oracle's Elixir para deduplicacao.", max_length=100, null=True, unique=True, verbose_name="ID Oracle's Elixir")),
                ('short_name', models.CharField(blank=True, max_length=20, verbose_name='Abreviacao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('leagues', models.ManyToManyField(blank=True, related_name='teams', to='analytics.league', verbose_name='Ligas')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome (in-game)')),
                ('oe_playerid', models.CharField(blank=True, help_text="Identificador unico do jogador no Oracle's Elixir.", max_length=100, null=True, unique=True, verbose_name="ID Oracle's Elixir")),
                ('position', models.CharField(choices=[('top', 'Top'), ('jng', 'Jungle'), ('mid', 'Mid'), ('bot', 'Bot'), ('sup', 'Support')], max_length=20, verbose_name='Posicao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='analytics.team', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.CharField(help_text="Identificador unico da partida no Oracle's Elixir.", max_length=200, unique=True, verbose_name='ID do Jogo')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('split', models.CharField(blank=True, help_text='Spring, Summer, etc.', max_length=50, verbose_name='Split')),
                ('patch', models.CharField(blank=True, max_length=20, verbose_name='Patch')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('game_length', models.FloatField(blank=True, null=True, verbose_name='Duracao (minutos)')),
                ('playoffs', models.BooleanField(default=False, verbose_name='Playoffs')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('blue_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_side_matches', to='analytics.team', verbose_name='Time Azul')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='analytics.league', verbose_name='Liga')),
                ('red_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_side_matches', to='analytics.team', verbose_name='Time Vermelho')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='analytics.team', verbose_name='Vencedor')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('Blue', 'Azul'), ('Red', 'Vermelho')], max_length=4, verbose_name='Lado')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Vencedor')),
                ('kills', models.IntegerField(default=0, verbose_name='Abates')),
                ('deaths', models.IntegerField(default=0, verbose_name='Mortes')),
                ('assists', models.IntegerField(default=0, verbose_name='Assistencias')),
                ('total_gold', models.FloatField(default=0, verbose_name='Ouro Total')),
                ('dragons', models.IntegerField(default=0, verbose_name='Dragoes')),
                ('barons', models.IntegerField(default=0, verbose_name='Baroes')),
                ('towers', models.IntegerField(default=0, verbose_name='Torres')),
                ('heralds', models.IntegerField(default=0, verbose_name='Arautos')),
                ('voidgrubs', models.IntegerField(default=0, verbose_name='Voidgrubs')),
                ('inhibitors', models.IntegerField(default=0, verbose_name='Inibidores')),
                ('first_blood', models.BooleanField(default=False, verbose_name='Primeiro Sangue')),
                ('first_dragon', models.BooleanField(default=False, verbose_name='Primeiro Dragao')),
                ('first_herald', models.BooleanField(default=False, verbose_name='Primeiro Arauto')),
                ('first_baron', models.BooleanField(default=False, verbose_name='Primeiro Barao')),
                ('first_tower', models.BooleanField(default=False, verbose_name='Primeira Torre')),
                ('golddiffat10', models.FloatField(blank=True, null=True, verbose_name='Diferenca de Ouro aos 10min')),
                ('golddiffat15', models.FloatField(blank=True, null=True, verbose_name='Diferenca de Ouro aos 15min')),
                ('xpdiffat10', models.FloatField(blank=True, null=True, verbose_name='Diferenca de XP aos 10min')),
                ('xpdiffat15', models.FloatField(blank=True, null=True, verbose_name='Diferenca de XP aos 15min')),
                ('csdiffat10', models.FloatField(blank=True, null=True, verbose_name='Diferenca de CS aos 10min')),
                ('csdiffat15', models.FloatField(blank=True, null=True, verbose_name='Diferenca de CS aos 15min')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_stats', to='analytics.match', verbose_name='Partida')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='analytics.team', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Estatistica do Time na Partida',
                'verbose_name_plural': 'Estatisticas dos Times nas Partidas',
                'unique_together': {('match', 'team')},
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20, verbose_name='Posicao')),
                ('champion', models.CharField(blank=True, max_length=100, verbose_name='Campeao')),
                ('kills', models.IntegerField(default=0, verbose_name='Abates')),
                ('deaths', models.IntegerField(default=0, verbose_name='Mortes')),
                ('assists', models.IntegerField(default=0, verbose_name='Assistencias')),
                ('cs', models.FloatField(default=0, help_text='Total de minions e monstros abatidos.', verbose_name='CS Total')),
                ('total_gold', models.FloatField(default=0, verbose_name='Ouro Total')),
                ('damage_to_champions', models.FloatField(default=0, verbose_name='Dano a Campeoes')),
                ('vision_score', models.FloatField(default=0, verbose_name='Pontuacao de Visao')),
                ('wards_placed', models.IntegerField(default=0, verbose_name='Sentinelas Colocadas')),
                ('wards_destroyed', models.IntegerField(default=0, verbose_name='Sentinelas Destruidas')),
                ('kda', models.FloatField(default=0, verbose_name='KDA')),
                ('cs_per_min', models.FloatField(default=0, verbose_name='CS por Minuto')),
                ('gold_per_min', models.FloatField(default=0, verbose_name='Ouro por Minuto')),
                ('damage_per_min', models.FloatField(default=0, verbose_name='Dano por Minuto')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='analytics.match', verbose_name='Partida')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='analytics.player', verbose_name='Jogador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_stats', to='analytics.team', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Estatistica do Jogador na Partida',
                'verbose_name_plural': 'Estatisticas dos Jogadores nas Partidas',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
