# Generated by Django 4.2.7 on 2026-01-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatchstats',
            name='first_inhibitor',
            field=models.BooleanField(default=False, verbose_name='Primeiro Inibidor'),
        ),
    ]
