# Generated by Django 4.2.7 on 2026-01-26 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_teammatchstats_first_inhibitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEloRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_rating', models.FloatField(default=1500.0, verbose_name='ELO Rating')),
                ('matches_played', models.IntegerField(default=0, verbose_name='Partidas Jogadas')),
                ('last_change', models.FloatField(default=0.0, verbose_name='Ultima Variacao')),
                ('last_match_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Ultima Partida')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elo_rating', to='analytics.team', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'ELO Rating',
                'verbose_name_plural': 'ELO Ratings',
                'ordering': ['-elo_rating'],
            },
        ),
    ]
