# Generated by Django 4.2.7 on 2026-02-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_teamelorating'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esports_game_id', models.CharField(help_text='ID do jogo na API LoL Esports.', max_length=50, unique=True, verbose_name='Game ID (LoL Esports)')),
                ('blue_team_code', models.CharField(max_length=20, verbose_name='Codigo Time Azul')),
                ('red_team_code', models.CharField(max_length=20, verbose_name='Codigo Time Vermelho')),
                ('blue_team_name', models.CharField(blank=True, max_length=200, verbose_name='Nome Time Azul')),
                ('red_team_name', models.CharField(blank=True, max_length=200, verbose_name='Nome Time Vermelho')),
                ('blue_team_db_id', models.IntegerField(blank=True, help_text='FK para Team.id (nao FK real para evitar dependencia).', null=True, verbose_name='ID DB Time Azul')),
                ('red_team_db_id', models.IntegerField(blank=True, help_text='FK para Team.id (nao FK real para evitar dependencia).', null=True, verbose_name='ID DB Time Vermelho')),
                ('match_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Partida')),
                ('draft_data', models.JSONField(blank=True, help_text="Dict com picks: {'blue_top': 'Ksante', ...}", null=True, verbose_name='Draft')),
                ('final_stats', models.JSONField(blank=True, help_text='Dict com kills, gold, towers, dragons, barons por lado.', null=True, verbose_name='Stats Finais')),
                ('players_data', models.JSONField(blank=True, help_text="Dict com {'blue': [...], 'red': [...]} jogadores.", null=True, verbose_name='Dados dos Jogadores')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Snapshot de Jogo ao Vivo',
                'verbose_name_plural': 'Snapshots de Jogos ao Vivo',
                'ordering': ['-updated_at'],
            },
        ),
    ]
